version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'php'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'javascript'
    commit-message:
      prefix: 'chore'
      include: 'scope'
