name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto Approve
        if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v4
